version: "3"

services:
    web:
        build: web
        image: trip-meal-web
        env_file: .env
        environment:
            - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/$tripmealdb
        networks:
            - banana
        ports:
            - ${SERVER_PORT}:${SERVER_PORT}
        depends_on:
            - db
    db: 
        build: db  
        image: trip-meal-db
        expose: 
            - 3306
        networks:
            - banana
        volumes:
            - ./db/db_data:/var/lib/mysql

volumes:
    trip-meal:

networks:
    banana:
