version: "3"

services:
    web:
        build: web
        image: grosclara/trip-meal-web
        env_file: .env
        environment:
            - DATABASE_URL=mysql://root:${MYSQL_ROOT_PASSWORD}@db:3306/tripmealdb
        networks:
            - banana
        ports:
            - ${SERVER_PORT}:${SERVER_PORT}
        depends_on:
            - db
    db: 
        build: db  
        image: grosclara/trip-meal-db
        env_file: .env
        expose: 
            - 3306
        networks:
            - banana
        volumes:
            - db-data:/var/lib/mysql

volumes:
    db-data:

networks:
    banana:
